src/Entity/Data.php
<?php declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Ignore;

#[ORM\Table(name: 'data')]
#[ORM\Entity(repositoryClass: \App\Repository\DataRepository::class)]
class Data
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    #[Ignore]
    protected ?int $id = null;

    #[ORM\ManyToOne(targetEntity: 'Station', inversedBy: 'datas')]
    #[ORM\JoinColumn(name: 'station_id', referencedColumnName: 'id')]
    protected ?Station $station = null;

    #[ORM\Column(type: 'datetime', nullable: false)]
    protected ?\DateTime $dateTime = null;

    #[ORM\Column(type: 'float', nullable: false)]
    protected ?float $value = null;

    #[ORM\Column(type: 'smallint', nullable: false)]
    protected ?int $pollutant = null;

    #[ORM\Column(type: 'string', length: 32, nullable: true)]
    private ?string $tag = null;

    public function setId(int $id): Data
    {
        $this->id = $id;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStation(): ?Station
    {
        return $this->station;
    }

    public function setStation(Station $station): Data
    {
        $this->station = $station;

        return $this;
    }

    public function getStationId(): ?int
    {
        if ($this->station) {
            return $this->station->getId();
        }

        return null;
    }

    public function getDateTimeFormatted(): string
    {
        return $this->dateTime->format('Y-m-d H:i:s');
    }

    public function getDateTime(): \DateTimeInterface
    {
        return $this->dateTime;
    }

    public function setDateTime(\DateTimeInterface $dateTime): Data
    {
        $this->dateTime = $dateTime;

        return $this;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): Data
    {
        $this->value = $value;

        return $this;
    }

    public function getPollutant(): ?int
    {
        return $this->pollutant;
    }

    public function setPollutant(int $pollutant): Data
    {
        $this->pollutant = $pollutant;

        return $this;
    }

    public function getProvider(): ?string
    {
        return $this->station->getProvider();
    }

    public function isIndexable(): bool
    {
        $dateTime = new \DateTimeImmutable();
        $dateTime->sub(new \DateInterval('P1W'));

        return $dateTime >= $this->dateTime;
    }

    public function getTag(): ?string
    {
        return $this->tag;
    }

    public function setTag(?string $tag): self
    {
        $this->tag = $tag;

        return $this;
    }
}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Data;
use AppBundle\Entity\Station;
use AppBundle\Pollution\Box\Box;
use AppBundle\Pollution\Pollutant\CO;
use AppBundle\Pollution\Pollutant\NO2;
use AppBundle\Pollution\Pollutant\O3;
use AppBundle\Pollution\Pollutant\PM10;
use AppBundle\Pollution\Pollutant\PollutantInterface;
use AppBundle\Pollution\Pollutant\SO2;
use AppBundle\Repository\DataRepository;
use Caldera\GeoBasic\Coord\Coord;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="display", options = { "expose" = true })
     */
    public function indexAction(Request $request)
    {
        $latitude = $request->query->get('latitude');
        $longitude = $request->query->get('longitude');

        if (!$latitude || !$longitude) {
            return $this->render('AppBundle:Default:select.html.twig');
        }

        $coord = new Coord(
            $latitude,
            $longitude
        );

        $stationList = $this->findNearestStations($coord);

        $dataList = $this->getDataListFromStationList($stationList);

        $boxList = $this->getBoxListFromDataList($dataList);

        $boxList = $this->decorateBoxList($boxList);

        return $this->render(
            'AppBundle:Default:view.html.twig',
            [
                'boxList' => $boxList
            ]
        );
    }

    protected function findNearestStations(Coord $coord): array
    {
        $finder = $this->container->get('fos_elastica.finder.air.station');

        $geoFilter = new \Elastica\Filter\GeoDistance(
            'pin',
            [
                'lat' => $coord->getLatitude(),
                'lon' => $coord->getLongitude()
            ],
            '10km'
        );

        $filteredQuery = new \Elastica\Query\Filtered(new \Elastica\Query\MatchAll(), $geoFilter);

        $query = new \Elastica\Query($filteredQuery);

        $query->setSize(15);
        $query->setSort(
            [
                '_geo_distance' =>
                    [
                        'pin' =>
                            [
                                $coord->getLatitude(),
                                $coord->getLongitude()
                            ],
                        'order' => 'asc',
                        'unit' => 'km'
                    ]
            ]
        );

        $results = $finder->find($query);

        return $results;
    }

    protected function getDataListFromStationList(array $stationList): array
    {
        $dataList = [
            PollutantInterface::POLLUTANT_PM10 => null,
            PollutantInterface::POLLUTANT_O3 => null,
            PollutantInterface::POLLUTANT_NO2 => null,
            PollutantInterface::POLLUTANT_SO2 => null,
            PollutantInterface::POLLUTANT_CO => null,
        ];

        foreach ($stationList as $station) {
            foreach ($dataList as $pollutant => $data) {
                if (!$data) {
                    $data = $this->checkStationData($station, $pollutant);

                    if ($data) {
                        $dataList[$pollutant] = $data;
                    }
                }
            }
        }

        return $dataList;
    }

    protected function checkStationData(Station $station, string $pollutant): ?Data
    {
        /** @var DataRepository $repository */
        $repository = $this->getDoctrine()->getRepository('AppBundle:Data');

        return $repository->findLatestDataForStationAndPollutant($station, $pollutant);
    }

    protected function getPollutantById(int $pollutantId): PollutantInterface
    {
        switch ($pollutantId) {
            case 1: return new PM10();
            case 2: return new O3();
            case 3: return new NO2();
            case 4: return new SO2();
            case 5: return new CO();
        }
    }

    protected function getBoxListFromDataList(array $dataList): array
    {
        $boxList = [];

        foreach ($dataList as $data) {
            if ($data) {
                $boxList[] = new Box($data);
            }
        }

        return $boxList;
    }

    protected function decorateBoxList(array $boxList): array
    {
        /** @var Box $box */
        foreach ($boxList as $box) {
            $data = $box->getData();

            $pollutant = $this->getPollutantById($data->getPollutant());
            $level = $pollutant->getPollutionLevel()->getLevel($data);

            $box
                ->setStation($data->getStation())
                ->setPollutant($pollutant)
                ->setPollutionLevel($level)
            ;
        }
        return $boxList;
    }

}

src/Caldera/StaticmapBundle/Controller/DefaultController.php
<?php

namespace Caldera\StaticmapBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('CalderaStaticmapBundle:Default:index.html.twig');
    }
}

templates/Default/_box.html.twig
{% if view_model %}
    {% if combined is defined and combined == true %}
     {% set combined = true %}
    {% else %}
     {% set combined = false %}
    {% endif %}

    {% if linkToStation is defined and linkToStation == true and view_model.station.stationCode %}
        {% set stationLink = true %}
    {% else %}
        {% set stationLink = false %}
    {% endif %}

    {% if showStationTitle is defined and showStationTitle != false and view_model.station.stationCode %}
        {% set stationTitle = true %}
    {% else %}
        {% set stationTitle = false %}
    {% endif %}

    {% if not combined %}
    <div class="card card-inverse mb-2">
    {% endif %}

    <div class="card-body text-white text-center box {{ view_model.pollutant.identifier }}" style="background-color: {{ pollution_color(view_model) }}" data-station-code="{{ view_model.station.stationCode }}" data-station-latitude="{{ view_model.station.latitude }}" data-station-longitude="{{ view_model.station.longitude }}" data-station-color="{{ pollution_color_name(view_model) }}" data-pollution-level="{{ view_model.pollutionLevel }}" data-station-map="{{ view_model.showOnMap }}">
        {% if stationLink %}<a href="{{ path('station', { 'stationCode': view_model.station.stationCode }) }}" class="no-underline text-white" title="Weitere Luftmesswerte der Station {{ view_model.station.stationCode }}{% if view_model.station.city %} aus {{ view_model.station.city.name }}{% endif %}">{% endif %}
        <h4 class="card-title">
            {{ view_model.data.value|number_format(view_model.pollutant.decimals, ',', '.') }} {{ view_model.pollutant.unitHtml|raw }}
        </h4>
        {% if stationLink %}</a>{% endif %}

        <p class="card-text">
            <a href="{{ path('limits') }}#{{ view_model.pollutant.identifier }}" class="btn btn-sm text-white" title="Weitere Informationen über den Luftschadstoff {{ view_model.pollutant.name }}">
                <i class="fa fa-info-circle"></i> {{ view_model.pollutant.name }}
            </a>
        </p>

        {% if stationLink %}<a href="{{ path('station', { 'stationCode': view_model.station.stationCode }) }}" class="no-underline text-white" title="Weitere Luftmesswerte der Station {{ view_model.station.stationCode }}{% if view_model.station.city %} aus {{ view_model.station.city.name }}{% endif %}">{% endif %}

        <p class="card-text">
        {% if stationTitle %}
            {% if view_model.station.title %}
                {{ view_model.station.title }}<br />
            {% else %}
                {{ view_model.station.stationCode }}<br />
            {% endif %}
        {% endif %}

        <small>
            <span title="{{ view_model.data.dateTime|date('d.m.Y H:i', 'Europe/Berlin') }} Uhr">
                <i class="fa fa-clock-o"></i> <time data-time-ago-timestamp="{{ view_model.data.dateTime|date('U') }}">{{ view_model.data.dateTime|date('d.m.Y H:i', 'Europe/Berlin') }}&nbsp;Uhr</time>
            </span>
            {% if stationTitle %}
            <br /><i class="fa fa-compass"></i> {{ view_model.distance|number_format(2, ',', '.') }} km entfernt
            {% endif %}
            {% if view_model.data.station.network and stationTitle %}
            <br />
            {{ view_model.data.station.network.name }}
            {% endif %}
        </small>

        </p>
        {% if stationLink %}</a>{% endif %}
    </div>

    {% if not combined %}
    </div>
    {% endif %}
{% endif %}

templates/Default/_pollutant.html.twig
<div class="row">
        <div class="card-group">
            {% for view_model in pollutant %}
            {% include 'Default/_box.html.twig' with { 'view_model': view_model, 'showStationTitle': showStationTitle, 'combined': combined } %}
            {% endfor %}
        </div>
</div>

templates/Default/_station.html.twig
{% if linkToStation is defined and linkToStation == true %}
<a href="{{ path('station', { 'stationCode': station.stationCode }) }}" class="no-underline">
{% endif %}
    <div class="card station" data-latitude="{{ station.latitude }}" data-longitude="{{ station.longitude }}" data-station-code="{{ station.stationCode }}" data-station-color="{{ max_pollution_color_name(pollutantList) }}">
    {% if showMap is not defined or showMap == true %}
        <div id="map-station-{{ station.stationCode }}" class="map card-img-top" style="height: 33.33vh;"></div>
        {% endif %}
        <div class="card-body">
            <h4 class="card-title">
                Messstation {{ station.stationCode }}
            </h4>
            <h6 class="card-sutitle text-muted">
                {% if not linkToStation is defined and station.city %}
                <a href="{{ path('show_city', { citySlug: station.city.slug }) }}" title="Übersicht über {{ station.city.name }}">
                    {{ station.title }}
                </a>
                {% else %}
                {{ station.title }}
                {% endif %}
            </h6>

            {% if description is defined %}
            <p class="card-text">
                {{ description }}
            </p>
            {% endif %}

            {% if station.stationType and station.areaType %}
            <p class="card-text text-muted">
                Stationstyp: {{ station.stationType|readable_enum|trans({}, 'messages', 'de') }}, {{ station.areaType|readable_enum|trans({}, 'messages', 'de') }}
                {% if station.network %}
                <br />
                {{ station.network.name }}
                {% endif %}
            </p>
            {% endif %}
        </div>

        {% for pollutant in pollutantList %}
            {% include 'Default/_pollutant.html.twig' with { 'pollutant': pollutant, 'showStationTitle': false, 'combined': true } %}
        {% endfor %}
    </div>

{% if linkToStation is defined and linkToStation == true %}
</a>
{% endif %}

templates/Default/display.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
<div class="container">
    <div class="row mb-2">
        <div class="col-12 text-center">
            {% if city %}
            <h3>
                Aktuelle Luftmesswerte aus {{ city.name }}
            </h3>
            {% elseif cityName %}
            <h3>
                Aktuelle Luftmesswerte aus {{ cityName }}
            </h3>
            {% else %}
            <h3>
                Aktuelle Messwerte aus deiner Umgebung
            </h3>
            {% endif %}

            <p class="lead">
                Es wurden die folgenden Schadstoffwerte aus Messstationen deiner Umgebung ermittelt:
            </p>
        </div>
    </div>

    <div class="card coord" data-latitude="{{ coord.latitude }}" data-longitude="{{ coord.longitude }}">
        {% if showMap is not defined or showMap == true %}
            <div id="coord-map" class="coord-map card-img-top" style="height: 33.33vh;"></div>
        {% endif %}

        {% for pollutant in pollutantList %}
            {% include 'Default/_pollutant.html.twig' with { 'pollutant': pollutant, 'showStationTitle': true, 'linkToStation': true, 'combined': true } %}
        {% endfor %}
    </div>

    {% if city %}
    <div class="row mt-2">
        <div class="col-12 text-center">
            <a href="{{ path('show_city', { citySlug: city.slug }) }}" class="btn btn-primary" title="Zeige weitere Schadstoff-Messwerte aus {{ city.name }}">
                Weitere Messwerte aus {{ city.name }}
            </a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/Default/no_stations.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="alert alert-info">
                Leider sind in deinem näheren Umfeld keine Messstationen zur Luftqualität im Betrieb. Du kannst aber aus der folgenden Liste Stationen in deiner Region einsehen.
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/Default/select.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-12 text-center">
            <p>
                Luft<sup class="text-primary">jetzt</sup> zeigt dir die aktuellen Schadstoffkonzentrationen wie Feinstaub oder Stickoxiden in deiner Umgebung an.
            </p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div id="geolocation-failed" class="alert alert-info d-none">
                Dein Standort konnte leider nicht automatisch bestimmt werden. Du kannst aber deine Postleitzahl eingeben, um Messwerte aus deiner Umgebung abzufragen.
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-12 col-lg-6 offset-lg-3 text-center">
            <h4>
                Ortsangabe
            </h4>

            <form method="get" action="{{ path('display') }}">
                <div class="input-group mb-3">
                    <input type="text" class="form-control form-control-lg typeahead" id="query" name="query" placeholder="Suchbegriff, Postleitzahl, Stadtname…" />
                    <button class="btn btn-primary btn-lg locate-button" type="button" title="Deinen Aufenthaltsort automatisch bestimmen">
                        <i class="fa fa-location-arrow"></i>
                    </button>
                </div>

                <div class="form-group">
                    <button id="search-button" type="submit" class="btn btn-primary btn-lg">
                        Weiter
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/Default/station.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="h3">
                    Messwerte der Station {{ station.stationCode }}
                </h2>

                <p class="lead">
                    An der Station {{ station.stationCode }}{% if station.city %} in <a href="{{ path('show_city', { citySlug: station.city.slug }) }}" title="Zeige weitere Schadstoff-Messwerte aus {{ station.city.name }} an">{{ station.city.name }}</a>{% endif %} wurden zuletzt die folgenden Werte gemessen:
                </p>
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-12">
                {% include 'Default/_station.html.twig' with { 'station': station, 'pollutantList': pollutantList } %}
            </div>
        </div>

        <div class="row mt-2">
            <div class="col-12 text-center">
                <div class="btn-group-vertical">
                    {% if station.city %}
                    <a href="{{ path('show_city', { citySlug: station.city.slug }) }}" class="btn btn-secondary" title="Zeige weitere Schadstoff-Messwerte aus {{ station.city.name }} an">
                        <i class="fa fa-university"></i>
                        weitere Messwerte aus {{ station.city.name }}
                    </a>
                    {% endif %}

                    {% if feature('station_history') %}
                        <a href="{{ path('station_history', { stationCode: station.stationCode }) }}" class="btn btn-secondary" title="Frühere Messwerte dieser Station">
                            <i class="fa fa-line-chart"></i>
                            frühere Messwerte dieser Station
                        </a>
                    {% endif %}

                    {% if station.provider == 'ld' %}
                        <a href="http://maps.sensor.community/#15/{{ station.latitude }}/{{ station.longitude }}" class="btn btn-secondary" title="Diese Station auf Sensor.Community anzeigen">
                            <i class="fa fa-map-marker"></i>
                            auf Sensor.Community anzeigen
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}